import { describe, it, expect } from 'vitest';
import { deriveMockStructure } from './data';
import type { ManuscriptSummary } from './types';

const BASE: ManuscriptSummary = {
  id:        'ms_1',
  title:     'The Lantern Keeper\'s Daughter',
  wordCount: 80000,
  updatedAt: '2026-01-01T00:00:00.000Z',
};

// ── Front matter ──────────────────────────────────────────────────

describe('deriveMockStructure — front matter', () => {
  it('always produces title-page, copyright, dedication in that order', () => {
    const front = deriveMockStructure(BASE).filter(i => i.type === 'front');
    expect(front.map(i => i.subtype)).toEqual(['title-page', 'copyright', 'dedication']);
  });

  it('title-page and copyright are auto-generated', () => {
    const items = deriveMockStructure(BASE);
    expect(items.find(i => i.subtype === 'title-page')?.isAutoGenerated).toBe(true);
    expect(items.find(i => i.subtype === 'copyright')?.isAutoGenerated).toBe(true);
  });

  it('copyright is marked required', () => {
    const items = deriveMockStructure(BASE);
    expect(items.find(i => i.subtype === 'copyright')?.isRequired).toBe(true);
  });

  it('title-page and copyright have confidence 1.0', () => {
    const items = deriveMockStructure(BASE);
    expect(items.find(i => i.subtype === 'title-page')?.confidence).toBe(1.0);
    expect(items.find(i => i.subtype === 'copyright')?.confidence).toBe(1.0);
  });
});

// ── Back matter ───────────────────────────────────────────────────

describe('deriveMockStructure — back matter', () => {
  it('always ends with about-author', () => {
    const items = deriveMockStructure(BASE);
    expect(items.at(-1)?.subtype).toBe('about-author');
    expect(items.at(-1)?.type).toBe('back');
  });
});

// ── Body chapters ─────────────────────────────────────────────────

describe('deriveMockStructure — body chapters', () => {
  it('maps each chapter title to a body chapter item', () => {
    const ms = { ...BASE, chapters: [{ title: 'Opening' }, { title: 'Rising' }] };
    const body = deriveMockStructure(ms).filter(i => i.type === 'body');
    expect(body).toHaveLength(2);
    expect(body[0]).toMatchObject({ subtype: 'chapter', title: 'Opening' });
    expect(body[1]).toMatchObject({ subtype: 'chapter', title: 'Rising' });
  });

  it('detects part titles by pattern and marks them subtype part', () => {
    const ms = {
      ...BASE,
      chapters: [
        { title: 'Part One' },
        { title: 'Chapter A' },
        { title: 'Part Two' },
        { title: 'Chapter B' },
      ],
    };
    const body = deriveMockStructure(ms).filter(i => i.type === 'body');
    expect(body.map(i => i.subtype)).toEqual(['part', 'chapter', 'part', 'chapter']);
  });

  it('detects numeric part titles', () => {
    const ms = { ...BASE, chapters: [{ title: 'Part 3' }, { title: 'Chapter X' }] };
    const body = deriveMockStructure(ms).filter(i => i.type === 'body');
    expect(body[0].subtype).toBe('part');
  });

  it('handles an empty chapters array', () => {
    const items = deriveMockStructure({ ...BASE, chapters: [] });
    expect(items.filter(i => i.type === 'body')).toHaveLength(0);
    expect(items.filter(i => i.type === 'front').length).toBeGreaterThan(0);
    expect(items.filter(i => i.type === 'back').length).toBeGreaterThan(0);
  });

  it('handles undefined chapters', () => {
    const items = deriveMockStructure(BASE); // no chapters key
    expect(items.filter(i => i.type === 'body')).toHaveLength(0);
  });
});

// ── Confidence & flagging ─────────────────────────────────────────

describe('deriveMockStructure — confidence', () => {
  it('flags exactly the 4th non-part chapter at 0.71', () => {
    const ms = {
      ...BASE,
      chapters: [
        { title: 'Ch 1' },
        { title: 'Ch 2' },
        { title: 'Ch 3' },
        { title: 'Ch 4' }, // ← 4th, should be flagged
        { title: 'Ch 5' },
      ],
    };
    const chapters = deriveMockStructure(ms).filter(i => i.subtype === 'chapter');
    expect(chapters[3].confidence).toBe(0.71);
    expect(chapters[3].flag).toMatch(/H2/);
    expect(chapters[0].flag).toBeUndefined();
    expect(chapters[4].flag).toBeUndefined();
  });

  it('non-flagged chapters have confidence between 0.87 and 0.97', () => {
    const ms = {
      ...BASE,
      chapters: [{ title: 'Alpha' }, { title: 'Beta' }, { title: 'Gamma' }],
    };
    const chapters = deriveMockStructure(ms).filter(i => i.subtype === 'chapter');
    for (const ch of chapters) {
      expect(ch.confidence).toBeGreaterThanOrEqual(0.87);
      expect(ch.confidence).toBeLessThanOrEqual(0.97);
    }
  });

  it('parts always have confidence 0.97', () => {
    const ms = { ...BASE, chapters: [{ title: 'Part One' }, { title: 'Ch A' }] };
    const part = deriveMockStructure(ms).find(i => i.subtype === 'part');
    expect(part?.confidence).toBe(0.97);
  });
});

// ── Determinism ───────────────────────────────────────────────────

describe('deriveMockStructure — determinism', () => {
  it('returns identical confidence and wordCount on repeated calls', () => {
    const ms = { ...BASE, chapters: [{ title: 'A Stable Title' }] };
    const a = deriveMockStructure(ms);
    const b = deriveMockStructure(ms);
    const chA = a.find(i => i.subtype === 'chapter')!;
    const chB = b.find(i => i.subtype === 'chapter')!;
    expect(chA.confidence).toBe(chB.confidence);
    expect(chA.wordCount).toBe(chB.wordCount);
  });

  it('different chapter titles produce different confidence values', () => {
    const msA = { ...BASE, chapters: [{ title: 'Alpha Chapter' }] };
    const msB = { ...BASE, chapters: [{ title: 'Zeta Chapter' }] };
    const confA = deriveMockStructure(msA).find(i => i.subtype === 'chapter')!.confidence;
    const confB = deriveMockStructure(msB).find(i => i.subtype === 'chapter')!.confidence;
    expect(confA).not.toBe(confB);
  });
});

// ── Indices ───────────────────────────────────────────────────────

describe('deriveMockStructure — indices', () => {
  it('assigns sequential 1-based indices across all items', () => {
    const ms = { ...BASE, chapters: [{ title: 'Ch 1' }, { title: 'Ch 2' }] };
    const items = deriveMockStructure(ms);
    items.forEach((item, i) => expect(item.index).toBe(i + 1));
  });

  it('all items have unique ids', () => {
    const ms = { ...BASE, chapters: [{ title: 'A' }, { title: 'B' }, { title: 'C' }] };
    const ids = deriveMockStructure(ms).map(i => i.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});
