import type { DetectedItem, ManuscriptSummary, FrontMatterState, SetTypeState, ProofWarning } from './types';
import { THEME_DEFS } from './types';

/* ── Known snippets for demo manuscripts ─────────────────────────── */

const CHAPTER_SNIPPETS: Record<string, string> = {
  "the keeper's daughter":
    'The lighthouse stood at the end of the world, or so Maren had always believed. Her father had said as much the day he brought her there, a girl of six with salt already in her hair.',
  'salt in the lungs':
    'She learned to read the weather before she could read words. The clouds meant something different out here — not rain, exactly, but a particular silence that came before it.',
  'when the girls leave':
    'The village held its girls loosely, like water in cupped hands. Maren watched them go, one by one, to the mainland towns and the men who waited there.',
  'a letter from the harbour':
    'Dear Miss Winwood, the postmaster wrote, with regret we cannot forward correspondence to a lighthouse that does not officially—',
  "the postmaster's wife":
    'The letter had gone astray. It was not the first, and it would not be the last. The harbour kept its secrets the way all harbours do.',
  'glass and salt water':
    'She found the cache on a Tuesday, behind the false wall her father had built into the lamp room the year before her mother left.',
  'what the light finds':
    'A lighthouse does not find ships. It finds the dark between them. Maren had understood this long before she understood what the letters meant.',
  'the wreck, correctly':
    'The inquiry lasted three days. They called her father in on the second, and she was not permitted to sit with him. She waited outside in the rain.',
  inheritance:
    'She kept the letters in the order they had come, which was not the order in which they had been written.',
};

function getSnippet(title: string): string {
  return CHAPTER_SNIPPETS[title.toLowerCase()] ?? '';
}

/* ── Deterministic confidence/wc offset from title string ────────── */

function djb2(s: string): number {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = (h * 33 ^ s.charCodeAt(i)) >>> 0;
  return h;
}

function normHash(s: string): number {
  return (djb2(s) % 100) / 100; // 0.00–0.99
}

/* ── Public: derive a mock detected structure from a manuscript ───── */

export function deriveMockStructure(ms: ManuscriptSummary): DetectedItem[] {
  const items: DetectedItem[] = [];
  let idx = 1;

  /* Front matter — always present */
  items.push({
    id: 'fm-title',
    index: idx++,
    type: 'front',
    subtype: 'title-page',
    title: 'Title page',
    snippet: ms.title,
    wordCount: 0,
    confidence: 1.0,
    isAutoGenerated: true,
  });

  items.push({
    id: 'fm-copyright',
    index: idx++,
    type: 'front',
    subtype: 'copyright',
    title: 'Copyright',
    snippet: `© 2026 ${ms.title.split(' ').pop()}. All rights reserved.`,
    wordCount: 0,
    confidence: 1.0,
    isAutoGenerated: true,
    isRequired: true,
  });

  items.push({
    id: 'fm-dedication',
    index: idx++,
    type: 'front',
    subtype: 'dedication',
    title: 'Dedication',
    snippet: 'For my mother, who left the porch light on.',
    wordCount: 18,
    confidence: 0.88,
  });

  /* Body chapters — derived from manuscript chapters array */
  const chapters = ms.chapters ?? [];
  const PART_RE  = /^part\s+(one|two|three|four|five|six|seven|eight|nine|ten|\d+)\b/i;

  const bodyChapters = chapters.filter(ch => !PART_RE.test(ch.title.trim()));
  const avgWc = bodyChapters.length > 0
    ? Math.round(ms.wordCount / bodyChapters.length)
    : 3200;

  let chapterNum = 0;
  let flaggedOne = false;

  for (let i = 0; i < chapters.length; i++) {
    const ch     = chapters[i];
    const isPart = PART_RE.test(ch.title.trim());

    if (isPart) {
      items.push({
        id: `body-${i}`,
        index: idx++,
        type: 'body',
        subtype: 'part',
        title: ch.title,
        snippet: '',
        wordCount: 0,
        confidence: 0.97,
      });
      continue;
    }

    chapterNum++;
    const isFlag = chapterNum === 4 && !flaggedOne;
    if (isFlag) flaggedOne = true;

    const h    = normHash(ch.title);
    const conf = isFlag ? 0.71 : 0.87 + h * 0.10;          // 0.87–0.97 normal
    const wc   = Math.round(avgWc * (0.85 + normHash(ch.title + '~wc') * 0.30)); // ±15%

    items.push({
      id: `body-${i}`,
      index: idx++,
      type: 'body',
      subtype: 'chapter',
      title: ch.title,
      snippet: getSnippet(ch.title),
      wordCount: wc,
      confidence: conf,
      flag: isFlag
        ? 'Detected from an H2 style. It might be a scene break inside the previous chapter.'
        : undefined,
    });
  }

  /* Back matter */
  items.push({
    id: 'bm-about',
    index: idx++,
    type: 'back',
    subtype: 'about-author',
    title: 'About the author',
    snippet: '',
    wordCount: 0,
    confidence: 0.87,
  });

  return items;
}

/* ── Derive proof warnings from existing state ────────────────────── */

export function deriveWarnings(
  structureItems: DetectedItem[],
  frontMatterState: FrontMatterState | null,
  typeSettingsState: SetTypeState | null,
): ProofWarning[] {
  const warnings: ProofWarning[] = [];

  // Flagged structure items → warn
  const chapters = structureItems.filter(i => i.subtype === 'chapter');
  chapters.forEach((ch, i) => {
    if (ch.flag) {
      warnings.push({
        level:    'warn',
        location: `Ch · ${String(i + 1).padStart(2, '0')}`,
        message:  `${ch.flag} Fix in Step 02.`,
        fixStep:  2,
      });
    }
  });

  // Long chapters (>700 words) → info
  chapters.forEach((ch, i) => {
    if (ch.wordCount > 700) {
      const pages = Math.ceil(ch.wordCount / 250);
      warnings.push({
        level:    'info',
        location: `Ch · ${String(i + 1).padStart(2, '0')}`,
        message:  `Long chapter (${ch.wordCount.toLocaleString()} words). Reads on Paperwhite as ${pages} swipes.`,
      });
    }
  });

  // Copyright auto-filled → info
  if (frontMatterState?.blocks.copyright.included) {
    warnings.push({
      level:    'info',
      location: 'FM · ii',
      message:  `Copyright year (${new Date().getFullYear()}) auto-filled from your profile.`,
    });
  }

  // TOC generated → ok
  warnings.push({
    level:    'ok',
    location: 'TOC',
    message:  'NCX + nav doc both generated.',
  });

  // Fonts → ok
  if (typeSettingsState) {
    const def = THEME_DEFS.find(t => t.key === typeSettingsState.theme);
    if (def) {
      warnings.push({
        level:    'ok',
        location: 'Fonts',
        message:  `${def.bodyFont} embedded · OFL · ~312 KB.`,
      });
    }
  }

  return warnings;
}
