export interface ManuscriptSummary {
  id: string;
  title: string;
  wordCount: number;
  updatedAt: string;
  _count?: { chapters: number };
  chapters?: { title: string }[];
}

export interface FormattingProjectRecord {
  id: string;
  manuscriptId: string;
  userId: string;
  currentStep: number;
  source: string | null;
  encoding: string;
  smartQuotes: string;
  uploadedDocxUrl: string | null;
  pastedContent: string | null;
  createdAt: string;
  updatedAt: string;
}

export type Encoding    = 'auto' | 'utf8' | 'win1252';
export type SmartQuotes = 'convert' | 'passthrough';

export interface IngestSettings {
  encoding:    Encoding;
  smartQuotes: SmartQuotes;
}

export type ItemType    = 'front' | 'body' | 'back';
export type ItemSubtype =
  | 'title-page'
  | 'copyright'
  | 'dedication'
  | 'epigraph'
  | 'chapter'
  | 'part'
  | 'scene-break'
  | 'about-author'
  | 'acknowledgments'
  | 'also-by';

export type ConfidenceThreshold = 'strict' | 'standard' | 'loose';
export type StructureView       = 'outline' | 'list' | 'tree';

export interface DetectedItem {
  id:             string;
  index:          number;
  type:           ItemType;
  subtype:        ItemSubtype;
  title:          string;
  snippet:        string;
  wordCount:      number;
  confidence:     number;     // 0–1; 1.0 for auto-generated items
  isAutoGenerated?: boolean;
  isRequired?:    boolean;
  isHidden?:      boolean;
  flag?:          string;     // human-readable reason for low confidence
}
