export interface ManuscriptSummary {
  id: string;
  title: string;
  wordCount: number;
  updatedAt: string;
  _count?: { chapters: number };
  chapters?: { title: string }[];
}

export interface FormattingProjectRecord {
  id: string;
  manuscriptId: string;
  userId: string;
  currentStep: number;
  source: string | null;
  encoding: string;
  smartQuotes: string;
  uploadedDocxUrl: string | null;
  pastedContent: string | null;
  frontMatter: string | null;
  typeSettings: string | null;
  createdAt: string;
  updatedAt: string;
}

export type Encoding    = 'auto' | 'utf8' | 'win1252';
export type SmartQuotes = 'convert' | 'passthrough';

export interface IngestSettings {
  encoding:    Encoding;
  smartQuotes: SmartQuotes;
}

export type ItemType    = 'front' | 'body' | 'back';
export type ItemSubtype =
  | 'title-page'
  | 'copyright'
  | 'dedication'
  | 'epigraph'
  | 'chapter'
  | 'part'
  | 'scene-break'
  | 'about-author'
  | 'acknowledgments'
  | 'also-by';

export type ConfidenceThreshold = 'strict' | 'standard' | 'loose';
export type StructureView       = 'outline' | 'list' | 'tree';

// ── Front matter ───────────────────────────────────────────────────

export type BlockKey = 'title-page' | 'copyright' | 'dedication' | 'epigraph' | 'also-by';

export interface TitlePageFields {
  title:    string;
  author:   string;
  year:     string;
  subtitle: string;
}

export interface CopyrightFields {
  text: string;
}

export interface DedicationFields {
  text: string;
}

export interface EpigraphFields {
  quote:       string;
  attribution: string;
}

export interface AlsoByEntry {
  id:    string; // local uuid for list key
  title: string;
  year:  string;
}

export interface AlsoByFields {
  entries: AlsoByEntry[];
}

export type BlockFields =
  | { key: 'title-page'; fields: TitlePageFields; included: true }
  | { key: 'copyright';  fields: CopyrightFields; included: true }
  | { key: 'dedication'; fields: DedicationFields; included: boolean }
  | { key: 'epigraph';   fields: EpigraphFields;   included: boolean }
  | { key: 'also-by';    fields: AlsoByFields;     included: boolean };

export interface FrontMatterState {
  selectedBlock: BlockKey;
  blocks: {
    'title-page': { fields: TitlePageFields; included: true };
    'copyright':  { fields: CopyrightFields; included: true };
    'dedication': { fields: DedicationFields; included: boolean };
    'epigraph':   { fields: EpigraphFields;   included: boolean };
    'also-by':    { fields: AlsoByFields;     included: boolean };
  };
}

const COPYRIGHT_TEMPLATE = (author: string, year: string) =>
  `Copyright © ${year} ${author}\n\nAll rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any form or by any means, including photocopying, recording, or other electronic or mechanical methods, without the prior written permission of the author, except in the case of brief quotations embodied in critical reviews and certain other non-commercial uses permitted by copyright law.`;

export function buildDefaultFrontMatter(
  title: string,
  author: string,
  existingJson: string | null,
): FrontMatterState {
  const year = String(new Date().getFullYear());

  const defaults: FrontMatterState = {
    selectedBlock: 'title-page',
    blocks: {
      'title-page': { included: true, fields: { title, author, year, subtitle: '' } },
      'copyright':  { included: true, fields: { text: COPYRIGHT_TEMPLATE(author, year) } },
      'dedication': { included: false, fields: { text: '' } },
      'epigraph':   { included: false, fields: { quote: '', attribution: '' } },
      'also-by':    { included: false, fields: { entries: [] } },
    },
  };

  if (!existingJson) return defaults;

  try {
    const saved = JSON.parse(existingJson) as Partial<FrontMatterState>;
    // Re-sync title/author from live manuscript data; preserve everything else
    const merged: FrontMatterState = {
      selectedBlock: saved.selectedBlock ?? defaults.selectedBlock,
      blocks: {
        'title-page': {
          included: true,
          fields: {
            ...(saved.blocks?.['title-page']?.fields ?? defaults.blocks['title-page'].fields),
            title,
            author,
          },
        },
        'copyright':  saved.blocks?.['copyright']  ?? defaults.blocks['copyright'],
        'dedication': saved.blocks?.['dedication'] ?? defaults.blocks['dedication'],
        'epigraph':   saved.blocks?.['epigraph']   ?? defaults.blocks['epigraph'],
        'also-by':    saved.blocks?.['also-by']    ?? defaults.blocks['also-by'],
      },
    };
    return merged;
  } catch {
    return defaults;
  }
}

export interface DetectedItem {
  id:             string;
  index:          number;
  type:           ItemType;
  subtype:        ItemSubtype;
  title:          string;
  snippet:        string;
  wordCount:      number;
  confidence:     number;     // 0–1; 1.0 for auto-generated items
  isAutoGenerated?: boolean;
  isRequired?:    boolean;
  isHidden?:      boolean;
  flag?:          string;     // human-readable reason for low confidence
}

// ── Type-setting ────────────────────────────────────────────────────

export type ThemeKey     = 'modern' | 'classic' | 'literary' | 'romance';
export type SceneBreakKey = 'stars' | 'fleuron' | 'dot' | 'dots';

export const SCENE_BREAK_SYMBOLS: Record<SceneBreakKey, string> = {
  stars:   '✦',
  fleuron: '❦',
  dot:     '·',
  dots:    '· · ·',
};

export interface ThemeDef {
  key:              ThemeKey;
  label:            string;
  bodyFont:         string;   // display name
  headingFont:      string;   // display name
  bodyStack:        string;   // CSS font-family value
  headingStack:     string;
  defaultSceneBreak: SceneBreakKey;
  defaultDropCap:   boolean;
  defaultSmallCaps: boolean;
}

export const THEME_DEFS: ThemeDef[] = [
  {
    key: 'modern', label: 'Modern',
    bodyFont: 'Source Serif 4', headingFont: 'Inter',
    bodyStack: "'Source Serif 4', Georgia, serif",
    headingStack: "Inter, system-ui, sans-serif",
    defaultSceneBreak: 'dots', defaultDropCap: false, defaultSmallCaps: false,
  },
  {
    key: 'classic', label: 'Classic',
    bodyFont: 'EB Garamond', headingFont: 'EB Garamond',
    bodyStack: "'EB Garamond', Garamond, Georgia, serif",
    headingStack: "'EB Garamond', Garamond, Georgia, serif",
    defaultSceneBreak: 'stars', defaultDropCap: true, defaultSmallCaps: true,
  },
  {
    key: 'literary', label: 'Literary',
    bodyFont: 'Lora', headingFont: 'Lora italic',
    bodyStack: "'Lora', Georgia, serif",
    headingStack: "'Lora', Georgia, serif",
    defaultSceneBreak: 'dot', defaultDropCap: true, defaultSmallCaps: false,
  },
  {
    key: 'romance', label: 'Romance',
    bodyFont: 'Crimson Pro', headingFont: 'Cormorant italic',
    bodyStack: "'Crimson Pro', 'Crimson Text', Georgia, serif",
    headingStack: "'Cormorant Garamond', 'Cormorant', Georgia, serif",
    defaultSceneBreak: 'fleuron', defaultDropCap: true, defaultSmallCaps: false,
  },
];

export interface SetTypeState {
  theme:       ThemeKey;
  dropCap:     boolean;
  dropCapLines: number;
  sceneBreak:  SceneBreakKey;
  smallCaps:   boolean;
}

export function buildDefaultTypeSettings(existingJson: string | null): SetTypeState {
  const defaults: SetTypeState = {
    theme:        'classic',
    dropCap:      true,
    dropCapLines: 4,
    sceneBreak:   'stars',
    smallCaps:    true,
  };
  if (!existingJson) return defaults;
  try {
    return { ...defaults, ...(JSON.parse(existingJson) as Partial<SetTypeState>) };
  } catch {
    return defaults;
  }
}
