import type { ReaderProfile } from './types';

export const READER_PROFILES: ReaderProfile[] = [
  {
    id: 'rdr_rosa',
    name: 'Rosa Pereira',
    initials: 'RP',
    tone: 'accent',
    location: 'Lisbon, Portugal',
    bio: 'Former archivist, now reads full-time. Particularly attentive to voice consistency and historical detail across period fiction. Has a deep familiarity with colonial and post-colonial European literary traditions.',
    availability: 'open',
    genrePreferences: ['Literary Fiction', 'Historical Fiction', 'Diaspora Fiction'],
    stats: {
      booksCompleted: 41,
      completionRate: 97,
      avgInlineComments: 54,
      authorsWorkedWith: 29,
      avgTurnaroundDays: 10,
    },
    joinedAt: '2024-04-12T00:00:00.000Z',
    email: 'rosa.pereira@readerslist.io',
  },
  {
    id: 'rdr_amir',
    name: 'Amir Hassan',
    initials: 'AH',
    tone: 'gold',
    location: 'Cairo, Egypt',
    bio: 'Reads widely in Arabic, French, and English literary fiction. Strong focus on cultural authenticity and character interiority. Particularly valuable for cross-cultural narratives and stories that move between languages or registers.',
    availability: 'open',
    genrePreferences: ['Literary Fiction', 'Diaspora Fiction', 'Translation Fiction'],
    stats: {
      booksCompleted: 28,
      completionRate: 92,
      avgInlineComments: 38,
      authorsWorkedWith: 19,
      avgTurnaroundDays: 14,
    },
    joinedAt: '2024-06-03T00:00:00.000Z',
    email: 'a.hassan@writersnetwork.co',
  },
  {
    id: 'rdr_cate',
    name: 'Cate Willoughby',
    initials: 'CW',
    tone: 'muted',
    location: 'Bath, UK',
    bio: 'Former librarian with a sharp eye for period anachronism and structural issues. Gives detailed, chapter-level notes with a particular focus on pacing and scene construction. Does not soften her observations.',
    availability: 'open',
    genrePreferences: ['Historical Fiction', 'Literary Fiction', 'Crime Fiction'],
    stats: {
      booksCompleted: 35,
      completionRate: 95,
      avgInlineComments: 61,
      authorsWorkedWith: 24,
      avgTurnaroundDays: 12,
    },
    joinedAt: '2024-03-20T00:00:00.000Z',
    email: 'cate.w@betareaders.net',
  },
  {
    id: 'rdr_priya',
    name: 'Priya Sharma',
    initials: 'PS',
    tone: 'ink',
    location: 'Toronto, Canada',
    bio: 'Academic background in postcolonial literature. Specialises in cross-cultural narratives and dual-timeline structures. Returns comprehensive chapter-by-chapter notes with particular attention to power dynamics and whose story is being centred.',
    availability: 'open',
    genrePreferences: ['Diaspora Fiction', 'Literary Fiction', 'Historical Fiction'],
    stats: {
      booksCompleted: 31,
      completionRate: 89,
      avgInlineComments: 47,
      authorsWorkedWith: 22,
      avgTurnaroundDays: 18,
    },
    joinedAt: '2024-05-15T00:00:00.000Z',
    email: 'priya.sharma@postcolonial.org',
  },
  {
    id: 'rdr_yuki',
    name: 'Yuki Adebayo',
    initials: 'YA',
    tone: 'paper',
    location: 'Tokyo, Japan',
    bio: 'Particular interest in narrative voice shifts and unreliable perspectives. Reads for both craft and emotional resonance. Brings an unusual cross-cultural lens to English-language fiction — especially useful for manuscripts testing what Western readers take for granted.',
    availability: 'open',
    genrePreferences: ['Literary Fiction', 'Speculative Fiction', 'Contemporary Fiction'],
    stats: {
      booksCompleted: 22,
      completionRate: 91,
      avgInlineComments: 33,
      authorsWorkedWith: 16,
      avgTurnaroundDays: 14,
    },
    joinedAt: '2024-09-01T00:00:00.000Z',
    email: 'yuki.adebayo@inbox.com',
  },
  {
    id: 'rdr_lena',
    name: 'Lena Brandt',
    initials: 'LB',
    tone: 'accent',
    location: 'Berlin, Germany',
    bio: 'Reads widely in European historical fiction with a strong command of German, French, and English literary traditions. Useful perspective on how stories travel across borders and what gets lost or distorted in the telling.',
    availability: 'open',
    genrePreferences: ['Historical Fiction', 'Literary Fiction', 'Translation Fiction'],
    stats: {
      booksCompleted: 27,
      completionRate: 93,
      avgInlineComments: 42,
      authorsWorkedWith: 20,
      avgTurnaroundDays: 14,
    },
    joinedAt: '2024-07-22T00:00:00.000Z',
    email: 'lena.brandt@readingclub.de',
  },
  {
    id: 'rdr_marcus',
    name: 'Marcus Osei',
    initials: 'MO',
    tone: 'gold',
    location: 'Accra, Ghana',
    bio: 'Fast reader, thorough notes on plot logic and character motivation. Former book reviewer for two West African literary magazines. Direct in his feedback — flags problems clearly and early, without softening them.',
    availability: 'open',
    genrePreferences: ['Literary Fiction', 'Crime Fiction', 'Memoir'],
    stats: {
      booksCompleted: 19,
      completionRate: 84,
      avgInlineComments: 28,
      authorsWorkedWith: 14,
      avgTurnaroundDays: 21,
    },
    joinedAt: '2024-11-10T00:00:00.000Z',
    email: 'marcus.osei@readers.co',
  },
  {
    id: 'rdr_sabine',
    name: 'Sabine Molière',
    initials: 'SM',
    tone: 'muted',
    location: 'Lyon, France',
    bio: 'Bilingual French/English reader with a focus on how memory and place function in literary fiction. Known for exceptionally fast turnaround and unusually precise marginal notes. Currently at capacity — not accepting new manuscripts until late 2026.',
    availability: 'closed',
    genrePreferences: ['Literary Fiction', 'Diaspora Fiction', 'Historical Fiction'],
    stats: {
      booksCompleted: 24,
      completionRate: 91,
      avgInlineComments: 45,
      authorsWorkedWith: 18,
      avgTurnaroundDays: 10,
    },
    joinedAt: '2024-04-30T00:00:00.000Z',
    email: 'sabine.m@lecteurs.fr',
  },
];

export const ALL_READER_GENRES = [
  ...new Set(READER_PROFILES.flatMap(r => r.genrePreferences)),
].sort();
