import { describe, it, expect, vi } from 'vitest';
import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { useState } from 'react';
import MarkUp from './MarkUp';
import type { DetectedItem, FormattingProjectRecord } from '../types';

// ── Fixtures ──────────────────────────────────────────────────────

const ITEMS: DetectedItem[] = [
  {
    id: 'fm-title', index: 1, type: 'front', subtype: 'title-page',
    title: 'Title page', snippet: '', wordCount: 0,
    confidence: 1.0, isAutoGenerated: true,
  },
  {
    id: 'body-1', index: 2, type: 'body', subtype: 'chapter',
    title: 'Chapter One', snippet: 'First words.', wordCount: 3000,
    confidence: 0.92,
  },
  {
    id: 'body-2', index: 3, type: 'body', subtype: 'chapter',
    title: 'Chapter Two', snippet: '', wordCount: 2800,
    confidence: 0.71, flag: 'Detected from an H2 style.',
  },
  {
    id: 'bm-about', index: 4, type: 'back', subtype: 'about-author',
    title: 'About the author', snippet: '', wordCount: 0,
    confidence: 0.87,
  },
];

// Stateful wrapper so mutations re-render the component
function Controlled({ initial = ITEMS }: { initial?: DetectedItem[] }) {
  const [items, setItems] = useState(initial);
  return (
    <MarkUp
      project={null}
      items={items}
      onItemsChange={setItems}
      onBack={vi.fn()}
      onAdvance={vi.fn()}
    />
  );
}

// ── Rendering ─────────────────────────────────────────────────────

describe('MarkUp — rendering', () => {
  it('renders all visible item titles in the outline list', () => {
    render(<Controlled />);
    expect(screen.getByText('Title page')).toBeInTheDocument();
    expect(screen.getByText('Chapter One')).toBeInTheDocument();
    expect(screen.getByText('Chapter Two')).toBeInTheDocument();
    expect(screen.getByText('About the author')).toBeInTheDocument();
  });

  it('shows the empty detail message when nothing is selected', () => {
    render(<Controlled />);
    expect(screen.getByText(/Select an item to review/i)).toBeInTheDocument();
  });

  it('shows status bar counts', () => {
    render(<Controlled />);
    expect(screen.getByText(/4 ITEMS/)).toBeInTheDocument();
    expect(screen.getByText(/2 CHAPTERS/)).toBeInTheDocument();
  });
});

// ── Selection ─────────────────────────────────────────────────────

describe('MarkUp — selection', () => {
  it('clicking a row opens its detail panel and shows the snippet', async () => {
    const user    = userEvent.setup();
    render(<Controlled />);
    const outline = screen.getByTestId('outline-list');
    await user.click(within(outline).getByText('Chapter One'));
    // Snippet renders as "First words." with wrapping curly quotes
    expect(screen.getByTestId('detail-panel')).toHaveTextContent('First words.');
  });

  it('clicking the same row a second time deselects it', async () => {
    const user    = userEvent.setup();
    render(<Controlled />);
    const outline = screen.getByTestId('outline-list');
    await user.click(within(outline).getByText('Chapter One'));
    await user.click(within(outline).getByText('Chapter One'));
    expect(screen.getByText(/Select an item to review/i)).toBeInTheDocument();
  });
});

// ── Filtering ─────────────────────────────────────────────────────

describe('MarkUp — filter tabs', () => {
  it('Front filter shows only front-matter items', async () => {
    const user = userEvent.setup();
    render(<Controlled />);
    await user.click(screen.getByText(/^Front/));
    expect(screen.getByText('Title page')).toBeInTheDocument();
    expect(screen.queryByText('Chapter One')).not.toBeInTheDocument();
  });

  it('Body filter shows only body items', async () => {
    const user = userEvent.setup();
    render(<Controlled />);
    await user.click(screen.getByText(/^Body/));
    expect(screen.getByText('Chapter One')).toBeInTheDocument();
    expect(screen.queryByText('Title page')).not.toBeInTheDocument();
  });

  it('Low conf filter shows only items below the threshold', async () => {
    const user = userEvent.setup();
    render(<Controlled />);
    await user.click(screen.getByText(/^Low conf/));
    // Chapter Two has confidence 0.71 < 0.85 (standard threshold)
    expect(screen.getByText('Chapter Two')).toBeInTheDocument();
    expect(screen.queryByText('Chapter One')).not.toBeInTheDocument();
  });

  it('Back filter shows only back-matter items', async () => {
    const user = userEvent.setup();
    render(<Controlled />);
    await user.click(screen.getByText(/^Back/));
    expect(screen.getByText('About the author')).toBeInTheDocument();
    expect(screen.queryByText('Chapter One')).not.toBeInTheDocument();
  });
});

// ── Operations ────────────────────────────────────────────────────

describe('MarkUp — confirm item', () => {
  it('confirm removes the flag so item no longer appears in the low-conf outline', async () => {
    const user    = userEvent.setup();
    render(<Controlled />);
    const outline = screen.getByTestId('outline-list');
    await user.click(within(outline).getByText('Chapter Two')); // flagged item
    await user.click(screen.getByText(/Confirm as Chapter/));
    // Switch to Low conf filter — Chapter Two now has confidence 0.95, above threshold
    await user.click(screen.getByText(/^Low conf/));
    expect(within(outline).queryByText('Chapter Two')).not.toBeInTheDocument();
  });
});

describe('MarkUp — hide item', () => {
  it('hiding an item removes it from the visible outline', async () => {
    const user    = userEvent.setup();
    render(<Controlled />);
    const outline = screen.getByTestId('outline-list');
    await user.click(within(outline).getByText('Chapter One'));
    // Click Hide in the ops grid (detail panel), not the bulk-bar button
    await user.click(within(screen.getByTestId('detail-panel')).getByText('Hide'));
    expect(within(outline).queryByText('Chapter One')).not.toBeInTheDocument();
  });
});

describe('MarkUp — rename item', () => {
  it('clicking the detail title button enters rename mode', async () => {
    const user   = userEvent.setup();
    render(<Controlled />);
    const outline = screen.getByTestId('outline-list');
    const detail  = screen.getByTestId('detail-panel');
    await user.click(within(outline).getByText('Chapter One'));
    // In the detail panel, the title renders as a <button>; clicking it activates the input
    await user.click(within(detail).getByRole('button', { name: /Chapter One/ }));
    expect(screen.getByRole('textbox')).toBeInTheDocument();
  });

  it('committing a rename updates the outline row', async () => {
    const user    = userEvent.setup();
    render(<Controlled />);
    const outline = screen.getByTestId('outline-list');
    const detail  = screen.getByTestId('detail-panel');
    await user.click(within(outline).getByText('Chapter One'));
    await user.click(within(detail).getByRole('button', { name: /Chapter One/ }));
    const input = screen.getByRole('textbox');
    await user.clear(input);
    await user.type(input, 'Renamed Chapter');
    await user.keyboard('{Enter}');
    expect(within(outline).getByText('Renamed Chapter')).toBeInTheDocument();
  });
});

describe('MarkUp — move up / move down', () => {
  it('move down swaps the item with its successor in the outline', async () => {
    const user    = userEvent.setup();
    render(<Controlled />);
    const outline = screen.getByTestId('outline-list');
    await user.click(within(outline).getByText('Chapter One'));
    await user.click(within(screen.getByTestId('detail-panel')).getByText('Move down ↓'));
    // Chapter Two should now appear before Chapter One in the outline
    const buttons = within(outline).getAllByRole('button');
    const titles  = buttons.map(b => b.textContent ?? '');
    const oneIdx  = titles.findIndex(t => t.includes('Chapter One'));
    const twoIdx  = titles.findIndex(t => t.includes('Chapter Two'));
    expect(twoIdx).toBeLessThan(oneIdx);
  });
});

describe('MarkUp — merge with previous', () => {
  it('merge removes the current item from the outline', async () => {
    const user    = userEvent.setup();
    render(<Controlled />);
    const outline = screen.getByTestId('outline-list');
    await user.click(within(outline).getByText('Chapter Two'));
    // Use the ops-grid Merge ↑ button inside the detail panel
    await user.click(within(screen.getByTestId('detail-panel')).getByText('Merge ↑'));
    expect(within(outline).queryByText('Chapter Two')).not.toBeInTheDocument();
  });
});

// ── Navigation callbacks ──────────────────────────────────────────

describe('MarkUp — footer callbacks', () => {
  it('Back button calls onBack', async () => {
    const user   = userEvent.setup();
    const onBack = vi.fn();
    render(
      <MarkUp
        project={null}
        items={ITEMS}
        onItemsChange={vi.fn()}
        onBack={onBack}
        onAdvance={vi.fn()}
      />,
    );
    await user.click(screen.getByText(/Step 01/));
    expect(onBack).toHaveBeenCalledOnce();
  });

  it('advance button calls onAdvance', async () => {
    const user      = userEvent.setup();
    const onAdvance = vi.fn();
    render(
      <MarkUp
        project={null}
        items={ITEMS}
        onItemsChange={vi.fn()}
        onBack={vi.fn()}
        onAdvance={onAdvance}
      />,
    );
    await user.click(screen.getByText(/Step 03/));
    expect(onAdvance).toHaveBeenCalledOnce();
  });
});
