import type { AuthorProfile } from './types';

export const AUTHOR_PROFILES: AuthorProfile[] = [
  {
    id: 'usr_billie',
    name: 'Billie Wolf',
    initials: 'BW',
    tone: 'gold',
    location: 'New Mexico, USA',
    bio: 'Billie Wolf writes literary fiction about memory, place, and what it means to belong somewhere. Her work has been described as "quietly devastating" and "luminously precise." She publishes independently through Billie Wolf Publishing.',
    writingProcess: 'I write in the early morning before the house wakes up — usually 5 to 7 AM, two cups of coffee, no music. I draft fast and revise slowly. My first drafts are rough and structural; I think of them as scaffolding. The real writing happens in revision, sentence by sentence. I keep a notebook for each project where I write the scenes I\'m afraid to write first, so the rest of the draft has somewhere to reach toward.',
    genres: ['Literary Fiction', 'Historical Fiction'],
    joinedAt: '2024-03-01T00:00:00.000Z',
    followerCount: 214,
    titles: 3,
    currentProject: {
      title: 'Hollow Meridian',
      genre: 'Speculative Fiction',
      wordCount: 62800,
      targetWordCount: 90000,
      status: 'drafting',
      startedAt: '2026-01-15T00:00:00.000Z',
    },
    activity: [
      { id: 1,  type: 'started',   text: 'Started drafting Hollow Meridian',                                  date: '2026-01-15T09:00:00.000Z' },
      { id: 2,  type: 'milestone', text: 'Reached 10,000 words on Hollow Meridian',                           date: '2026-01-28T10:00:00.000Z' },
      { id: 3,  type: 'published', text: 'The Salt Roads is now available in print via IngramSpark',          date: '2026-02-03T12:00:00.000Z' },
      { id: 4,  type: 'milestone', text: 'Reached 25,000 words on Hollow Meridian',                           date: '2026-02-18T10:00:00.000Z' },
      { id: 5,  type: 'revision',  text: 'Began final revisions on The Lantern Keeper\'s Daughter',           date: '2026-03-04T09:00:00.000Z' },
      { id: 6,  type: 'milestone', text: 'Reached 50,000 words on Hollow Meridian — past the midpoint',       date: '2026-03-22T10:00:00.000Z' },
      { id: 7,  type: 'chapter',   text: 'Completed Part Two of Hollow Meridian (Chapters 9–17)',             date: '2026-04-10T09:00:00.000Z' },
      { id: 8,  type: 'milestone', text: 'Reached 62,000 words on Hollow Meridian',                           date: '2026-04-30T10:00:00.000Z' },
    ],
    pendingQuestions: [
      {
        id: 101,
        submitterId: 'usr_alice',
        submitterName: 'Alice Morrow',
        question: 'How do you approach writing grief without sliding into sentimentality? Your work is devastating but never maudlin.',
        submittedAt: '2026-05-01T10:00:00.000Z',
      },
      {
        id: 102,
        submitterId: 'usr_james',
        submitterName: 'James Okonkwo',
        question: 'Does your early-morning writing routine ever conflict with insomnia or difficult nights? How do you protect that time?',
        submittedAt: '2026-05-03T14:00:00.000Z',
      },
      {
        id: 103,
        submitterId: 'usr_sarah',
        submitterName: 'Sarah Chen',
        question: 'What drew you toward speculative fiction for Hollow Meridian after two realist novels? Was it a deliberate pivot?',
        submittedAt: '2026-05-06T09:00:00.000Z',
      },
    ],
    qa: [
      {
        id: 1,
        question: 'How did you come up with the title The Salt Roads?',
        answer: 'The title came before the book did, which is unusual for me. I was reading about salt trade routes in the American Southwest and kept returning to the phrase — it had a weight to it. Salt preserves things. It also stings. The book needed both.',
        askedAt: '2026-02-10T00:00:00.000Z',
      },
      {
        id: 2,
        question: 'Do you outline or write into the dark?',
        answer: 'Both, depending on the book. The Salt Roads was outlined in detail because the dual timeline required it — I needed to know where the two threads would converge before I could write either one honestly. Hollow Meridian I\'m writing into the dark, which is terrifying and occasionally wonderful.',
        askedAt: '2026-03-01T00:00:00.000Z',
      },
      {
        id: 3,
        question: 'What do you read when you\'re drafting?',
        answer: 'I try to read nothing too close to what I\'m writing in terms of voice or subject. While drafting Hollow Meridian I\'ve been reading Toni Morrison essays and a lot of non-fiction about deep geological time. It keeps my prose from getting contaminated by someone else\'s rhythm.',
        askedAt: '2026-04-12T00:00:00.000Z',
      },
    ],
  },

  {
    id: 'usr_alice',
    name: 'Alice Morrow',
    initials: 'AM',
    tone: 'accent',
    location: 'Edinburgh, Scotland',
    bio: 'Alice Morrow writes historical fiction set at the edges of official records — stories about the people history tends to overlook. Her debut novel follows three generations of midwives in Victorian-era Scotland.',
    writingProcess: 'Research comes first, always. I spend months with primary sources before I write a word of prose. By the time I sit down to draft, I feel like I\'ve been living in the period already. I write in longhand first, then transcribe — the act of typing the draft again is a first edit. It sounds slow, and it is, but the pages that come out of it are much cleaner.',
    genres: ['Historical Fiction', 'Literary Fiction'],
    joinedAt: '2025-01-14T09:00:00.000Z',
    followerCount: 87,
    titles: 2,
    currentProject: {
      title: 'The Midwife\'s Ledger',
      genre: 'Historical Fiction',
      wordCount: 71200,
      targetWordCount: 80000,
      status: 'in-revision',
      startedAt: '2025-06-01T00:00:00.000Z',
    },
    activity: [
      { id: 1, type: 'started',     text: 'Started drafting The Midwife\'s Ledger',                       date: '2025-06-01T09:00:00.000Z' },
      { id: 2, type: 'milestone',   text: 'Reached 50,000 words on The Midwife\'s Ledger',                date: '2025-09-14T10:00:00.000Z' },
      { id: 3, type: 'beta_opened', text: 'Opened The Midwife\'s Ledger to beta readers',                 date: '2025-11-03T09:00:00.000Z' },
      { id: 4, type: 'revision',    text: 'Began structural revisions on The Midwife\'s Ledger',          date: '2026-01-20T09:00:00.000Z' },
      { id: 5, type: 'milestone',   text: 'Revised through Chapter 22 — the hardest section is done',    date: '2026-04-08T10:00:00.000Z' },
    ],
    qa: [
      {
        id: 1,
        question: 'How do you handle historical accuracy vs narrative licence?',
        answer: 'I have a rule: I won\'t invent a historical fact, but I will invent everything that history didn\'t record. So if a date or a law or a real person\'s documented action is known, I stick to it. Everything in between — the feelings, the conversations, the smell of a room — that\'s where the fiction lives.',
        askedAt: '2026-02-22T00:00:00.000Z',
      },
      {
        id: 2,
        question: 'What\'s the hardest part of writing historical fiction?',
        answer: 'Letting go of research. You accumulate so much — it becomes genuinely interesting in its own right — and then you have to make yourself forget most of it for the sake of the story. The reader doesn\'t need everything you know. They need to feel the world.',
        askedAt: '2026-03-15T00:00:00.000Z',
      },
    ],
  },

  {
    id: 'usr_james',
    name: 'James Okonkwo',
    initials: 'JO',
    tone: 'muted',
    location: 'Lagos, Nigeria',
    bio: 'James Okonkwo writes speculative fiction that sits at the intersection of climate science and ancestral memory. His work explores what we owe to futures we will not live to see.',
    writingProcess: 'I write in the evenings, after work, for about two hours. I need the day to have happened first — the friction of it, the ordinary accumulation of things going slightly wrong. That\'s where my best ideas come from. I keep a voice memo app open during the day and leave myself fragments. The evenings are for assembling them.',
    genres: ['Speculative Fiction', 'Climate Fiction'],
    joinedAt: '2025-02-20T11:30:00.000Z',
    followerCount: 62,
    titles: 1,
    currentProject: {
      title: 'When the Rivers Remember',
      genre: 'Speculative Fiction',
      wordCount: 34500,
      targetWordCount: 85000,
      status: 'drafting',
      startedAt: '2025-10-01T00:00:00.000Z',
    },
    activity: [
      { id: 1, type: 'started',   text: 'Started drafting When the Rivers Remember',             date: '2025-10-01T09:00:00.000Z' },
      { id: 2, type: 'milestone', text: 'Reached 10,000 words — the world is starting to cohere', date: '2025-11-12T10:00:00.000Z' },
      { id: 3, type: 'chapter',   text: 'Completed the prologue and first four chapters',        date: '2026-01-07T09:00:00.000Z' },
      { id: 4, type: 'milestone', text: 'Reached 25,000 words on When the Rivers Remember',      date: '2026-02-28T10:00:00.000Z' },
      { id: 5, type: 'milestone', text: 'Reached 34,000 words — past the first act',             date: '2026-04-19T10:00:00.000Z' },
    ],
    qa: [
      {
        id: 1,
        question: 'How much climate science research goes into your work?',
        answer: 'A significant amount, but I try to wear it lightly. The science is load-bearing — it has to be accurate enough that a scientist wouldn\'t wince — but the reader shouldn\'t feel like they\'re being educated. The speculative elements come from asking: what if the science is right, and what if the people are still recognisably human?',
        askedAt: '2026-03-08T00:00:00.000Z',
      },
      {
        id: 2,
        question: 'What draws you to the intersection of ancestral memory and climate?',
        answer: 'Because that\'s where the grief is. The communities most affected by climate change are often the ones with the deepest relationships to the land — relationships that span generations and include the dead. I\'m interested in what it means to mourn a place that is still, technically, there.',
        askedAt: '2026-04-01T00:00:00.000Z',
      },
    ],
  },

  {
    id: 'usr_sarah',
    name: 'Sarah Chen',
    initials: 'SC',
    tone: 'paper',
    location: 'San Francisco, CA',
    bio: 'Sarah Chen writes contemporary literary fiction about first-generation immigrant families and the stories that get mistranslated across languages and generations. She is working on her second novel.',
    writingProcess: 'I\'m a slow drafter and a fast reviser. I write maybe 300 words a day during a draft, but I reread everything each morning before I start. By the time I reach the end of a draft, the beginning has been revised ten times. My beta readers always say the first third is too polished — they\'re right. I\'m working on stopping myself.',
    genres: ['Literary Fiction', 'Contemporary'],
    joinedAt: '2025-04-03T16:00:00.000Z',
    followerCount: 41,
    titles: 1,
    currentProject: {
      title: 'Everything That Doesn\'t Translate',
      genre: 'Literary Fiction',
      wordCount: 58000,
      targetWordCount: 75000,
      status: 'drafting',
      startedAt: '2025-07-15T00:00:00.000Z',
    },
    activity: [
      { id: 1, type: 'started',   text: 'Started drafting Everything That Doesn\'t Translate',  date: '2025-07-15T09:00:00.000Z' },
      { id: 2, type: 'milestone', text: 'Reached 25,000 words',                                  date: '2025-10-02T10:00:00.000Z' },
      { id: 3, type: 'milestone', text: 'Reached 50,000 words — the book finally knows itself',  date: '2026-01-30T10:00:00.000Z' },
      { id: 4, type: 'chapter',   text: 'Finished Part Three — the hardest section',             date: '2026-04-22T09:00:00.000Z' },
    ],
    qa: [
      {
        id: 1,
        question: 'How autobiographical is your fiction?',
        answer: 'The feelings are always autobiographical. The facts almost never are. I write characters who feel the things I\'ve felt, in situations I\'ve invented to make those feelings as clear and as pressured as possible. The immigrant experience I write about is real. The specific families are not.',
        askedAt: '2026-03-20T00:00:00.000Z',
      },
    ],
  },

  {
    id: 'usr_vera',
    name: 'Vera Novak',
    initials: 'VN',
    tone: 'muted',
    location: 'Prague, Czech Republic',
    bio: 'Vera Novak writes psychological mysteries set in Central Europe. She is working on her debut novel, a thriller about an archivist who discovers that a series of Cold War-era deaths were never properly investigated.',
    writingProcess: 'I am new to this, so I am still finding my process. What I know so far: I need complete silence. I need a detailed outline. And I need to have met all my characters before I introduce them to each other — I write character histories that never appear in the text, just so I know who they are when they walk into a scene.',
    genres: ['Mystery', 'Psychological Thriller'],
    joinedAt: '2026-04-22T12:00:00.000Z',
    followerCount: 12,
    titles: 1,
    currentProject: {
      title: 'The Archive Beneath the Archive',
      genre: 'Psychological Thriller',
      wordCount: 18400,
      targetWordCount: 80000,
      status: 'drafting',
      startedAt: '2026-04-25T00:00:00.000Z',
    },
    activity: [
      { id: 1, type: 'started',   text: 'Started drafting The Archive Beneath the Archive', date: '2026-04-25T09:00:00.000Z' },
      { id: 2, type: 'milestone', text: 'Reached 10,000 words — the first act is taking shape', date: '2026-05-04T10:00:00.000Z' },
    ],
    qa: [],
  },
];
